WITH TEMP_HORAS AS (
	SELECT
	EMP_ID,
	--TIMESTAMP,
	--LAG(TIMESTAMP) OVER (PARTITION BY CAST(TIMESTAMP AS DATE), EMP_ID ORDER BY TIMESTAMP)
	CASE 
		WHEN DATEPART(MINUTE, TIMESTAMP) >= DATEPART(MINUTE, LAG(TIMESTAMP) OVER (PARTITION BY CAST(TIMESTAMP AS DATE), EMP_ID ORDER BY TIMESTAMP))
			THEN DATEPART(HOUR, TIMESTAMP) - DATEPART(HOUR, LAG(TIMESTAMP) OVER (PARTITION BY CAST(TIMESTAMP AS DATE), EMP_ID ORDER BY TIMESTAMP)) 
		ELSE DATEPART(HOUR, TIMESTAMP) - DATEPART(HOUR, LAG(TIMESTAMP) OVER (PARTITION BY CAST(TIMESTAMP AS DATE), EMP_ID ORDER BY TIMESTAMP)) - 1
	END AS DIF_HORAS
	FROM   ATTENDANCE
	WHERE  DATEPART(WEEKDAY, TIMESTAMP) IN (7, 1)
)

SELECT EMP_ID, SUM(DIF_HORAS) AS HORAS
FROM TEMP_HORAS
GROUP BY EMP_ID
ORDER BY DIF_HORAS DESC